### ISSUE TITLE
Materi Basic

### ISSUE THREAD

**Issue by nuraskiah** [bellshade/Golang#4]
### Description
Berikut adalah topik-topik yang akan dibahas dalam materi basic:
- [x] Pengenalan
- [x] Variabel dan tipe data (in progress)
- [x] Percabangan @frisconp
- [x] Perulangan @frisconp 
- [x] Array, slice, map ( done @slowy07 )
- [x] Function @nuraskiah 
- [x] Recursion
- [x] Pointer ( done @slowy07 )
- [x] type casting (done @slowy07 )
- [x] Struct ( done @slowy07 )
- [x] Interface ( done @slowy07 )
- [x] Defer, panic, recover ( done @slowy07 )

### Information for Contributors
Bagi teman-teman yang ingin melakukan kontribusi untuk topik-topik di atas, silahkan komen di dalam issue ini. Terima kasih.

#### Tasks
- Penjelasan dalam README.md
- File `.go` yang bisa dieksekusi

**Comment by nuraskiah** [comment]
silahkan @frisconp

**Comment by rizface** [comment]
untuk map,slice, array belum ada yang ambil, saya coba kontribusi ya

**Comment by nuraskiah** [comment]
> untuk map,slice, array belum ada yang ambil, saya coba kontribusi ya

Halo @rizface. Apakah jadi mengerjakan materi ini? Jika tidak maka akan dialihkan ke kontributor lain.

**Comment by slowy07** [comment]
list dari semua basic
```
1 . introduction
2 . operator logika
3.  variabel
4. constant
5. operator (aritmatika, relasional, logika, bitwise, penugasan)
6. perualangan
7. fungsi
8. scope
9. string
10. array
11. pointer
12. structure
13. slice
14. range looping
15. map
16. rekursif
17. type casting
18. interface
19. error handling
```
